export const mockRentalItems = [
  {
    id: '1',
    resortId: 'CERRO_CATEDRAL',
    category: 'SKI',
    name: 'Ski Atomic Redster',
    description: 'Ski de alto rendimiento para esquiadores avanzados. Perfecto para pistas preparadas y carving.',
    imageUrl: '/assets/rental/austria/ski/1.png',
    pricePerDay: 45.00,
    status: 'ACTIVE',
    variants: [
      {
        id: '1-1',
        size: '160cm',
        skillLevel: 'ADVANCED',
        gender: 'UNISEX',
        unitsTotal: 5,
        unitsAvailable: 3,
      },
      {
        id: '1-2',
        size: '170cm',
        skillLevel: 'ADVANCED',
        gender: 'UNISEX',
        unitsTotal: 3,
        unitsAvailable: 2,
      },
    ],
  },
  {
    id: '2',
    resortId: 'CERRO_CATEDRAL',
    category: 'SNOWBOARD',
    name: 'Snowboard Burton Custom',
    description: 'Snowboard versátil para todo tipo de terreno. Ideal para freeride y freestyle.',
    imageUrl: '/assets/rental/austria/ski/2.png',
    pricePerDay: 40.00,
    status: 'ACTIVE',
    variants: [
      {
        id: '2-1',
        size: '155cm',
        skillLevel: 'INTERMEDIATE',
        gender: 'UNISEX',
        unitsTotal: 4,
        unitsAvailable: 4,
      },
      {
        id: '2-2',
        size: '160cm',
        skillLevel: 'INTERMEDIATE',
        gender: 'UNISEX',
        unitsTotal: 4,
        unitsAvailable: 2,
      },
    ],
  },
  {
    id: '3',
    resortId: 'CHAPELCO',
    category: 'BOOTS',
    name: 'Botas Salomon X-Pro',
    description: 'Botas de ski cómodas y ajustables. Perfectas para principiantes e intermedios.',
    imageUrl: '/assets/rental/austria/ski/3.png',
    pricePerDay: 25.00,
    status: 'ACTIVE',
    variants: [
      {
        id: '3-1',
        size: '36',
        skillLevel: 'BEGINNER',
        gender: 'WOMEN',
        unitsTotal: 8,
        unitsAvailable: 6,
      },
      {
        id: '3-2',
        size: '38',
        skillLevel: 'BEGINNER',
        gender: 'WOMEN',
        unitsTotal: 6,
        unitsAvailable: 4,
      },
      {
        id: '3-3',
        size: '40',
        skillLevel: 'BEGINNER',
        gender: 'MEN',
        unitsTotal: 6,
        unitsAvailable: 5,
      },
    ],
  },
  {
    id: '4',
    resortId: 'LAS_LEÑAS',
    category: 'COMBO',
    name: 'Combo Completo Ski',
    description: 'Paquete completo que incluye ski, botas, bastones y casco. Ideal para principiantes.',
    imageUrl: '/assets/rental/austria/ski/1.png',
    pricePerDay: 60.00,
    status: 'ACTIVE',
    variants: [
      {
        id: '4-1',
        size: 'M',
        skillLevel: 'BEGINNER',
        gender: 'UNISEX',
        unitsTotal: 10,
        unitsAvailable: 7,
      },
      {
        id: '4-2',
        size: 'L',
        skillLevel: 'BEGINNER',
        gender: 'UNISEX',
        unitsTotal: 8,
        unitsAvailable: 5,
      },
    ],
  },
  {
    id: '5',
    resortId: 'VALLE_NEVADO',
    category: 'POLES',
    name: 'Bastones Leki',
    description: 'Bastones de aluminio ligeros y resistentes. Ajustables en altura.',
    imageUrl: '/assets/rental/austria/ski/2.png',
    pricePerDay: 15.00,
    status: 'OUT_OF_STOCK',
    variants: [
      {
        id: '5-1',
        size: '110cm',
        skillLevel: 'UNISEX',
        gender: 'UNISEX',
        unitsTotal: 0,
        unitsAvailable: 0,
      },
    ],
  },
];

export const mockResorts = [
  { id: 'CERRO_CATEDRAL', name: 'Cerro Catedral', region: 'Río Negro' },
  { id: 'CHAPELCO', name: 'Chapelco', region: 'Neuquén' },
  { id: 'LAS_LEÑAS', name: 'Las Leñas', region: 'Mendoza' },
  { id: 'VALLE_NEVADO', name: 'Valle Nevado', region: 'Chile' },
  { id: 'PORTILLO', name: 'Portillo', region: 'Chile' },
]; 